name: Main Build

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true

jobs:
  release:
    name: Increase version and tag

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Increase version
        run: |
          npm version ${{ github.event.inputs.new_version }}

      - name: Push new version
        run: |
          git push --follow-tags
