name: Version Increase

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true

jobs:
  release:
    name: Increase version and tag

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Configure Git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Checkout main
        run: |
          git checkout main

      - name: Tag current version
        run: |
          npm run tag

      - name: Increase version
        run: |
          npm --no-git-tag-version version ${{ github.event.inputs.new_version }}

      - name: Commit version
        run: |
          git commit -a -m "Version upgraded to ${{ github.event.inputs.new_version }}"

      - name: Push tag and new version
        run: |
          git push
          git push origin --tags
